# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f81a80b0bed365241176b726957bed9a9b81fe8713f10518591ff298cd8df1bc69348d595245316a59fec2e5531f16c5348ff6189667a00932331a87d9faa88

test:
  secret_key_base: 9cc17ac4f58a930a5e217318c8269a03f1f5e30bab3be90f4e09bf898a8bd71ee3b86575fde8fa9562f7749072ef66e7e902e232457b0215bb6d7b3cfeec5799

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
