# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

 development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  YELP_CONSUMER_KEY: <%= ENV['YELP_CONSUMER_KEY'] %>
  YELP_CONSUMER_SECRET: <%= ENV['YELP_CONSUMER_SECRET'] %>
  YELP_TOKEN: <%= ENV['YELP_TOKEN'] %>
  YELP_TOKEN_SECRET: <%= ENV['YELP_TOKEN_SECRET'] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  YELP_CONSUMER_KEY: <%= ENV['YELP_CONSUMER_KEY'] %>
  YELP_CONSUMER_SECRET: <%= ENV['YELP_CONSUMER_SECRET'] %>
  YELP_TOKEN: <%= ENV['YELP_TOKEN'] %>
  YELP_TOKEN_SECRET: <%= ENV['YELP_TOKEN_SECRET'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV['SECRET_TOKEN'] %>
  YELP_CONSUMER_KEY: <%= ENV['YELP_CONSUMER_KEY'] %>
  YELP_CONSUMER_SECRET: <%= ENV['YELP_CONSUMER_SECRET'] %>
  YELP_TOKEN: <%= ENV['YELP_TOKEN'] %>
  YELP_TOKEN_SECRET: <%= ENV['YELP_TOKEN_SECRET'] %>


